language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer update --quiet
  - mysql < phpunit/db/create_table.sql
  - php -i

script: 
  - ./vendor/bin/phpunit -c phpunit/phpunit.xml.dist
    
git:
  depth: 5
