language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer update
  - mysql < phpunit/db/create_table.sql

script: 
  - phpunit -c phpunit/phpunit.xml.dist
  - ./make_phpdoc.sh
