CREATE USER 'tango'@'localhost' IDENTIFIED BY 'tango';

GRANT USAGE ON *.* TO 'tango'@'localhost' IDENTIFIED BY 'tango' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, 
CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, 
ALTER ROUTINE, EXECUTE ON `tango_test`.* TO 'tango'@'localhost';
